CREATE DATABASE SupportTicketManagement

CREATE TABLE Roles 
(
    Id      INT PRIMARY KEY IDENTITY(1,1),
    Name    NVARCHAR(20) NOT NULL UNIQUE CHECK (Name IN ('MANAGER', 'SUPPORT', 'USER'))
);

CREATE TABLE Users 
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL, 
    RoleId INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);
select * from Users
CREATE TABLE Tickets 
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (Status IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
    Priority NVARCHAR(10) NOT NULL DEFAULT 'MEDIUM' CHECK (Priority IN ('LOW','MEDIUM','HIGH')),
    CreatedBy INT NOT NULL,
    AssignedTo INT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
    FOREIGN KEY (AssignedTo) REFERENCES Users(Id)
);

CREATE TABLE TicketComments 
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    TicketId INT NOT NULL,
    UserId INT NOT NULL,
    Comment NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (TicketId) REFERENCES Tickets(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE TicketStatusLogs 
(
    Id INT PRIMARY KEY IDENTITY(1,1),
    TicketId INT NOT NULL,
    OldStatus NVARCHAR(20) NOT NULL CHECK (OldStatus IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
    NewStatus NVARCHAR(20) NOT NULL
        CHECK (NewStatus IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),

    ChangedBy INT NOT NULL,

    ChangedAt DATETIME2 NOT NULL DEFAULT GETDATE(),

    FOREIGN KEY (TicketId) REFERENCES Tickets(Id) ON DELETE CASCADE,

    FOREIGN KEY (ChangedBy) REFERENCES Users(Id)
);

INSERT INTO Roles (Name) VALUES ('MANAGER');
INSERT INTO Roles (Name) VALUES ('SUPPORT');
INSERT INTO Roles (Name) VALUES ('USER');